p16_2: p16_2.o readline.o quicksort.o
		gcc -o p16_2 p16_2.o readline.o quicksort.o
		
p16_2.o: p16_2.c readline.h quicksort.h
		gcc -c p16_2.c
		
quicksort.o: quicksort.c quicksort.h
		gcc -c quicksort.c

readline.o: readline.c readline.h
		gcc -c readline.c